enum DbApiErrorType {
  DB_EXCEPTION = "DB_EXCEPTION",
  UNKNOWN_EXCEPTION = "UNKNOWN_EXCEPTION",
  NOT_FOUND_EXCEPTION = "NOT_FOUND_EXCEPTION",
  REQUEST_EXCEPTION = "REQUEST_EXCEPTION",
  FILESTATION_EXCEPTION = "FILESTATION_EXCEPTION",
}

export { DbApiErrorType };
