enum FileStationError {
  UNKNOWN_ERROR = "UNKNOWN_ERROR",
  NO_PARAMETER = "NO_PARAMETER",
  API_METHOD_OR_VERSION_NOT_SPECIFIED = "API_METHOD_OR_VERSION_NOT_SPECIFIED",
  API_DOES_NOT_EXIST = "API_DOES_NOT_EXIST",
  METHOD_DOES_NOT_EXIST = "METHOD_DOES_NOT_EXIST",
  VERSION_UNSUPPORTED = "VERSION_UNSUPPORTED",
  PERMISSION_DENIED = "PERMISSION_DENIED",
  SESSION_TIMEOUT = "SESSION_TIMEOUT",
  DUPLICATE_LOGIN_INTERRUPTED_SESSION = "DUPLICATE_LOGIN_INTERRUPTED_SESSION",
  SID_NOT_FOUND = "SID_NOT_FOUND",
}

export { FileStationError };
